ParamTab: Gray out parameters on disconnect
bitcraze/crazyflie-clients-python pull request #480
Opened 2021-03-09 13:01 UTC by jonasdn

This is instead of removing all of them, so that you can still see parameters and logging variables when disconnected.

Closes #250

2021-03-09 13:51 UTC, evoggy requested changes
Looks nice! But it seems as if the old data is not cleared when the Crazyflie re-connects again so the list of parameters keeps on growing.

For closing #250 I guess the same change would have to be done to the Log TOC tab so these values are also kept after disconnect.

2021-03-09 13:55 UTC, jonasdn commented
> Looks nice! But it seems as if the old data is not cleared when the Crazyflie re-connects again so the list of parameters keeps on growing.
> 
> For closing #250 I guess the same change would have to be done to the Log TOC tab so these values are also kept after disconnect.

Thank you! I thought I tested the reconnect case! Will make sure to reset the model on connect!

2021-03-10 08:54 UTC, jonasdn commented
I have updated this to make sure it clears on re-connect. And also grays out the LogTab.

2021-03-10 09:57 UTC, merged

2021-03-10 09:57 UTC, evoggy commented
Great, looks good to me!